### PR TITLE
Major update

### PR DESCRIPTION
**Pull request by Alivekeep**
- Rewrited coffeescript to pure JS ES6
- Rebuild features as a modules
- Migration from JSON config store to dotenv (evironment variables)
- Added logging to each WS points (client connect/disconnect/messages)
- Removed unused dependencies
- Updated dependencies to current versions
- Replaced node-uuid -> uuid
- Updated documentation
- Added health check (Readiness/Liveness probe for Kubernetes) - WebSocket server and RabbitMQ avialability

> PR for Docker image https://github.com/docker-taiga/events/pull/1

### CODE REVIEW

**Comment by bameda** [comment]
Wow, it looks awesome, thank you very much for your time and effort. We have to do an in-depth review and test that everything works correctly but in a quick quick review I found two changes that I can't understand:

- Why do you replace `repository.url` in `package.json` with the url of your fork repo?  
- And why do you delete `CODE_OF_CONDUCT.md`?

Thanks again, it is a pleasure to receive this kind of contributions

**Comment by Alivekeep** [comment]
> Wow, it looks awesome, thank you very much for your time and effort. We have to do an in-depth review and test that everything works correctly but in a quick quick review I found two changes that I can't understand:
> 
> * Why do you replace `repository.url` in `package.json` with the url of your fork repo?
> * And why do you delete `CODE_OF_CONDUCT.md`?
> 
> Thanks again, it is a pleasure to receive this kind of contributions

Hello there!

> Why do you replace repository.url in package.json with the url of your fork repo?

Of course, it's should be original URL (I replaced this automatically xD)

> And why do you delete CODE_OF_CONDUCT.md?

My apologies, was removed automatically.

**Comment by blackandred** [comment]
Any news on this?

**Comment by juanfran** [comment]
Sorry for taking so long. Thanks @Alivekeep it's awesome!! We're working on [taiga-front-next](https://github.com/taigaio/taiga-front-next) a complete rewrite and we want this to be deployed in taiga.io when taiga-next is ready, could you change the target branch to taiga-next in this repo? Thanks!

**Comment by Alivekeep** [comment]
Hello there! Target branch was changed.

**Comment by juanfran** [comment]
thanks, we will be using it with [taiga-front-next](https://github.com/taigaio/taiga-front-next)

**Pull request merged**
